// 新增表单项
export const EDITOR_ADD_ITEM = 'EDITOR_ADD_ITEM'
export type EDITOR_ADD_ITEM = typeof EDITOR_ADD_ITEM
// 修改单个表单属性
export const EDITOR_UPDATE_ITEM = 'EDITOR_UPDATE_ITEM'
export type EDITOR_UPDATE_ITEM = typeof EDITOR_UPDATE_ITEM
// 修改表单
export const EDITOR_UPDATE_FORM = 'EDITOR_UPDATE_FORM'
export type EDITOR_UPDATE_FORM = typeof EDITOR_UPDATE_FORM
// 设置当前选中表单项
export const EDITOR_SET_ACTIVE_ITEM = 'EDITOR_SET_ACTIVE_ITEM'
export type EDITOR_SET_ACTIVE_ITEM = typeof EDITOR_SET_ACTIVE_ITEM
// 删除表单项
export const EDITOR_REMOVE_ITEM = 'EDITOR_REMOVE_ITEM'
export type EDITOR_REMOVE_ITEM = typeof EDITOR_REMOVE_ITEM
// 重置表单
export const EDITOR_REST_FORM = 'EDITOR_REST_FORM'
export type EDITOR_REST_FORM = typeof EDITOR_REST_FORM
