export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export type CHANGE_LANGUAGE = typeof CHANGE_LANGUAGE

export const CHANGE_LOADING = 'CHANGE_LOADING'
export type CHANGE_LOADING = typeof CHANGE_LOADING

export const CHANGE_COLOR = 'CHANGE_COLOR'
export type CHANGE_COLOR = typeof CHANGE_COLOR

export const SET_LOGIN_INFO = 'SET_LOGIN_INFO'
export type SET_LOGIN_INFO = typeof SET_LOGIN_INFO
